# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-27 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
