# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-27 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20200227_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='lng',
            new_name='longitude',
        ),
    ]
