# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20200227_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price_per_night',
            new_name='price_per_day',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
